const strings = {
    appHeader: 'SAMARITAN',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    signIn : 'Sign In',
    newTo: 'New to Samaritan? ',
    signUp: 'Sign Up',
    emailError: 'Email is required!',
    passwordError: 'Please enter a valid password! Characters between 8 to 20, at least one letter and one number.',
    fnameError: 'Please enter valid First Name!',
    lnameError: 'Last Name is required!',
    contactnumberError: 'Please enter valid Contact Number!',
    countryError: 'Country is required!',
    locationError: 'Location is required!',
    confirmPasswordError: 'Confirm password is required',
    loginError: 'Email and Password are required!',
    invalidUser: 'User is invalid!',
    invalidEmail: 'Please enter valid email',
    continueBtn: 'Continue',
    firstName: 'First Name',
    lastName: 'Last Name',
    contactNumber: 'Contact Number (XXX-XXX-XXXX)',
    country: 'Country',
    location: 'Location',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    emptyfieldError: 'All fields are required',
    contactformatError: 'Contact number should contain numbers only',
    pwdmatchError: 'passwords do not match',
    country: 'Country',
    searchHintText: 'What are you looking for?',
    dendConnectionRequest: 'Send Connection Request'
  };

  export default strings;