const strings = {
    appHeader: 'SAMARITAN',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    signIn : 'Sign In',
    newTo: 'New to Samaritan? ',
    signUp: 'Sign Up',
    emailError: 'Email is required!',
    passwordError: 'Password is required!',
    fnameError: 'First name is required!',
    fnameformatError: 'Invalid first name format',
    lnameError: 'Last Name is required!',
    contactnumberError: 'Contact Number is required!',
    countryError: 'Country is required!',
    locationError: 'Location is required!',
    confirmPasswordError: 'Confirm password is required',
    loginError: 'Email and Password are required!',
    invalidUser: 'User is invalid!',
    invalidEmail: 'Please enter valid email',
    continueBtn: 'Continue',
    firstName: 'First Name',
    lastName: 'Last Name',
    contactNumber: 'Contact Number',
    country: 'Country',
    location: 'Location',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    emptyfieldError: 'All fields are required',
    contactformatError: 'Contact number should contain numbers only',
    pwdmatchError: 'passwords do not match',
  };

  export default strings;