const strings = {
    appHeader: 'SAMARITAN',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    signIn : 'Sign In',
    newTo: 'New to Samaritan? ',
    signUp: 'Sign Up',
    save: 'Save',
    update: 'Update',
    emailError: 'Email is required!',
    passwordError: 'Please enter a valid password! Characters between 8 to 20, at least one letter and one number.',
    fnameError: 'Please enter valid First Name!',
    lnameError: 'Last Name is required!',
    contactnumberError: 'Please enter valid Contact Number!',
    countryError: 'Country is required!',
    locationError: 'Location is required!',
    addressError: 'Address is required!',
    confirmPasswordError: 'Confirm password is required',
    loginError: 'Email and Password are required!',
    invalidUser: 'User is invalid!',
    invalidEmail: 'Please enter valid email',
    continueBtn: 'Continue',
    firstName: 'First Name',
    lastName: 'Last Name',
    contactNumber: 'Contact Number (XXX-XXX-XXXX)',
    country: 'Country',
    location: 'Location',
    email: 'Email',
    address: 'Address',
    password: 'Password',
    city: 'City',
    province: 'Province',
    services: 'Services',
    organization: 'Organization Name',
    orgType: 'Oraganization Type',
    confirmPassword: 'Confirm Password',
    emptyfieldError: 'All fields are required',
    contactformatError: 'Contact number should contain numbers only',
    pwdmatchError: 'passwords do not match',
    country: 'Country',
    searchHintText: 'What are you looking for?',
    dendConnectionRequest: 'Send Connection Request',
    apiError: 'Unable to fetch request! Server must be down!!',
    forgotPasswordHeading: 'Forgot your password?',
    loading: 'Loading...',
    notification : 'Notifications',
    notificationServiceAcc: 'Your Connection request for Accommodation has been sent Successfully!',
    notificationServiceJob: 'Your Connection request for Part time job has been sent Successfully!',
    notificationMsg: 'Your Connection request for Part time job has been sent Accepted by Mentor!',
    signOutTitle: 'Sign Out?',
    signOutMsg: 'Are you sure, you want to sign out?',
    no: 'No',
    yes: 'Yes',
    signOut: 'Sign Out',
    home: 'Home',
    request: 'Requests',
    details: 'Details',
    seekerLbl: 'Seeker',
    mentorLbl: 'Mentor',
    typeLbl: 'Type',
    statusLbl: 'Status',
    serviceLbl: 'Service',
    ratingLbl: 'Rating',
    actionLbl: 'Action',
    nameLbl: 'Name',
    phoneLbl: 'Phone',
    targetCityLbl: 'Target City',
    welcomeMsg: 'Welcome Admin!',
    userAnalytics: 'Users Analytics',
    seekers: 'Seekers',
    mentors: 'Mentors',
    serviceAnalytics: 'Services Analytics',
    ongoing: 'Ongoing',
    completed: 'Completed',
    failed: 'Failed',
    pending: 'Pending',
    mentorStatus: 'Mentor Status',
    applied: 'Applied',
    invited: 'Invited',
    approved: 'Approved',
    addedTitle: 'Added!',
    done: 'Done',
    organizationType: 'Organization Type',
    paymentStatusUpdated: 'Payment Status Updated!',
    mentor: 'Mentor:',
    seeker: 'Seeker:',
    service: 'Service:',
    paymentStatus: 'Payment Status:',
    updatePaymentStatus: 'Update Payment Status:',
    typeHere: 'Type your message...',
    onBoardStatus: 'Onboard Status Updated!',
    location: 'Location:',
    onBoard: 'Onboard Status:',
    visaStatus: 'Visa Status:',
    strikeCount: 'Strike Count:',
    rating: 'Rating:',
    updateMentorStatus: 'Update Mentor Status:',
    adminNotification: 'You have a payment to be done!',
    dashboard: 'Dashboard',
    connections: 'Connections',
    payments: 'Payments',
    addCollaborator: 'Add Collaborator',
    paymentDetails: 'Payment Detail',
    mentorDetails: 'Mentor Detail'
  };

  export default strings;